telegram:
  # test bot 7023267442:AAGhUiMH3GunS96Z9tD_DWfALIZYZjiESzA
  token: 7023267442:AAGhUiMH3GunS96Z9tD_DWfALIZYZjiESzA
  adminId: 6266824055

ticker:
  duration: 5s

trigger_times:
  - "4:40" # Fajr
  - "12:40" # Duhr
  - "16:25" # Asr
  - "18:05" # Maghrib
  - "1:35" # Isha

operation:
  verse_preference: enable

database:
  host: localhost
  port: 5432
  password: 12345
  user: postgres
  dbname: quran_daily_test # one_ayah_daily # quran_daily_test